### ISSUE TITLE
Contents of .mnc files are missing

### ISSUE THREAD

**Issue by tggadda** [IbisNeuronav/IbisExampleData#3]
When I try to use the Spine (and other) example files I always get the message that the .mnc files could not be opened and sometimes Ibis also crashes.  I looked at the contents of these files and they do not look right.  For example, in the SpineScene example, 0.mnc has the following contents: 
version https://git-lfs.github.com/spec/v1
oid sha256:3c055f5b1d770e3ff440a247374d1f4de52a2424d778cfc1b303c173ad9eeabe
size 148544

All the other .mnc files I've looked at have similar contents.

**Comment by nist-anka** [comment]
What is your work environment? 
git-lfs works well on Ubuntu 20.04 and Windows 10 professional.
Also works on Ubuntu 18.04

**Comment by errollgarner** [comment]
This error with incomplete files happens when git-lfs isn't installed on the system. Installing git-lfs on ubuntu 20.04 can be done with `apt-get install git-lfs`. I added the link to the git-lfs documentation in the repository readme file.
You may need to do a clean git clone of the repository in order for the changes to be applied after git-lfs is installed.
